name: ProjectEnd
version: '${project.version}'
main: projectend.projectend.ProjectEnd
api-version: 1.19
commands:
  random:
    usage: /<command>
    aliases: /random
    description: runs a random command which will return a random event
  debug:
    usage: /<command>
    aliases: /debug
    description: debug command for debugging
  badum:
    usage: /<command>
    aliases: /mira
    description: Look there's no logic to this thing...
  custommob:
    usage: /<command>
    aliases: /custom
    description: Spawns custom mob